"""Data models for LLM integration."""

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional

from refactron.core.models import CodeIssue


class SuggestionStatus(Enum):
    """Status of a refactoring suggestion."""

    PENDING = "pending"  # Generated, waiting for review
    VALIDATING = "validating"  # Being checked by safety gate
    APPROVED = "approved"  # User approved
    REJECTED = "rejected"  # User rejected
    APPLIED = "applied"  # Code changes applied
    FAILED = "failed"  # Failed application or safety check


@dataclass
class SafetyCheckResult:
    """Result of a safety gate validation."""

    passed: bool
    score: float  # 0.0 to 1.0
    issues: List[str]
    syntax_valid: bool = False
    side_effects: List[str] = field(default_factory=list)


@dataclass
class RefactoringSuggestion:
    """A refactoring suggestion generated by the LLM."""

    # Context
    issue: CodeIssue
    original_code: str
    context_files: List[str]  # Files used for context

    # LLM Output
    proposed_code: str
    explanation: str
    reasoning: str  # Chain of thought

    # Metadata
    model_name: str
    confidence_score: float  # Adjusted score (safety gate result)
    llm_confidence: float = 0.5  # Raw score from LLM response

    # State
    status: SuggestionStatus = SuggestionStatus.PENDING
    safety_result: Optional[SafetyCheckResult] = None

    # Tracking
    suggestion_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=time.time)

    def __post_init__(self) -> None:
        if self.safety_result is None:
            # Default empty safety result
            self.safety_result = SafetyCheckResult(
                passed=False, score=0.0, issues=["Not validated yet"]
            )
